# Generated by Django 3.0.3 on 2020-03-19 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('portfolio', '0005_auto_20200319_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='initiated',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 0, 53, 11, 167663)),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stock',
            field=models.CharField(default='Stock', max_length=100),
        ),
    ]
