# Generated by Django 3.0.3 on 2020-03-20 01:29

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('portfolio', '0010_auto_20200319_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='beta',
            field=models.DecimalField(decimal_places=6, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='dividend_rate',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='dividend_yield',
            field=models.DecimalField(decimal_places=6, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='forward_EPS',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='forward_PE',
            field=models.DecimalField(decimal_places=6, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='industry',
            field=models.CharField(default='NA', max_length=300),
        ),
        migrations.AddField(
            model_name='stock',
            name='market_cap',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='price_to_sales_12m',
            field=models.DecimalField(decimal_places=6, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='profit_margin',
            field=models.DecimalField(decimal_places=10, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='sector',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='stock',
            name='tradeable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='trailing_EPS',
            field=models.DecimalField(decimal_places=6, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='trailing_PE',
            field=models.DecimalField(decimal_places=6, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='inception',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trade',
            name='initiated',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 21, 28, 59, 954836)),
        ),
    ]
