# Generated by Django 3.0.4 on 2020-03-31 03:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('portfolio', '0013_auto_20200319_2134'),
        ]

    operations = [
        migrations.RemoveField(
                 model_name='long',
                 name='trade_ptr',
                 ),
        migrations.RemoveField(
                 model_name='longcall',
                 name='option_ptr',
                 ),
        migrations.RemoveField(
                 model_name='longput',
                 name='option_ptr',
                 ),
        migrations.RemoveField(
                 model_name='option',
                 name='trade_ptr',
                 ),
        migrations.DeleteModel(
                 name='Portfolio',
                 ),
        migrations.RemoveField(
                 model_name='short',
                 name='trade_ptr',
                 ),
        migrations.RemoveField(
                 model_name='shortcall',
                 name='option_ptr',
                 ),
        migrations.RemoveField(
                 model_name='shortput',
                 name='option_ptr',
                 ),
        migrations.RemoveField(
                 model_name='trade',
                 name='polymorphic_ctype',
                 ),
        migrations.RemoveField(
                 model_name='trade',
                 name='stock',
                 ),
        migrations.DeleteModel(
                 name='Long',
                 ),
        migrations.DeleteModel(
                 name='LongCall',
                 ),
        migrations.DeleteModel(
                 name='LongPut',
                 ),
        migrations.DeleteModel(
                 name='Option',
                 ),
        migrations.DeleteModel(
                 name='Short',
                 ),
        migrations.DeleteModel(
                 name='ShortCall',
                 ),
        migrations.DeleteModel(
                 name='ShortPut',
                 ),
        migrations.DeleteModel(
                 name='Stock',
                 ),
        migrations.DeleteModel(
                 name='Trade',
                 ),
        ]
