# Generated by Django 3.0.3 on 2020-03-23 01:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('portfolio', '0013_auto_20200319_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='summary',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='option',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2020, 6, 23, 1, 49, 45, 93934, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='inception',
            field=models.DateField(default=datetime.datetime(2020, 3, 23, 1, 49, 45, 93934, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trade',
            name='initiated',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 1, 49, 45, 93934, tzinfo=utc)),
        ),
    ]
