# Generated by Django 3.0.3 on 2020-03-23 02:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('portfolio', '0015_auto_20200322_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2020, 6, 23, 2, 6, 23, 868443, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='inception',
            field=models.DateField(default=datetime.datetime(2020, 3, 23, 2, 6, 23, 868443, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trade',
            name='initiated',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 2, 6, 23, 868443, tzinfo=utc)),
        ),
    ]
