# Generated by Django 3.0.3 on 2020-03-23 02:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('portfolio', '0020_long_longcall_longput_option_short_shortcall_shortput_stock_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2020, 6, 23, 2, 49, 57, 533624, tzinfo=utc)),
        ),
    ]
