# Generated by Django 3.0.3 on 2020-03-23 03:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('portfolio', '0021_auto_20200322_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='gain_loss',
            new_name='gain_loss_value',
        ),
        migrations.AddField(
            model_name='trade',
            name='gain_loss_percent',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2020, 6, 23, 3, 50, 40, 560945, tzinfo=utc)),
        ),
    ]
