# Generated by Django 3.0.4 on 2020-03-31 03:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('portfolio', '0022_auto_20200322_2350'),
        ('portfolio', '0015_long_longcall_longput_option_portfolio_short_shortcall_shortput_stock_trade'),
        ]

    operations = [
        ]
