# Generated by Django 3.0.4 on 2020-03-31 03:22

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('portfolio', '0024_auto_20200330_2321'),
        ]

    operations = [
        migrations.CreateModel(
                 name='Portfolio',
                 fields=[
                     ('id', models.AutoField(primary_key=True, serialize=False)),
                     ('name', models.CharField(default='Test', max_length=100)),
                     ('cash', models.DecimalField(decimal_places=2, max_digits=100)),
                     ('inception', models.DateField(default=django.utils.timezone.now)),
                     ('fee_rate', models.IntegerField(default=0)),
                     ],
                 ),
        migrations.CreateModel(
                 name='Stock',
                 fields=[
                     ('ticker', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                     ('name', models.CharField(max_length=200, unique=True)),
                     ('summary', models.TextField()),
                     ('sector', models.CharField(max_length=100)),
                     ('industry', models.CharField(max_length=300)),
                     ('dividend_rate', models.DecimalField(decimal_places=2, max_digits=100)),
                     ('beta', models.DecimalField(decimal_places=6, max_digits=100)),
                     ('trailing_PE', models.DecimalField(decimal_places=6, max_digits=100)),
                     ('market_cap', models.PositiveIntegerField(null=True)),
                     ('price_to_sales_12m', models.DecimalField(decimal_places=6, max_digits=100)),
                     ('forward_PE', models.DecimalField(decimal_places=6, max_digits=100)),
                     ('tradeable', models.BooleanField(default=True)),
                     ('dividend_yield', models.DecimalField(decimal_places=6, max_digits=100)),
                     ('forward_EPS', models.DecimalField(decimal_places=2, max_digits=100)),
                     ('profit_margin', models.DecimalField(decimal_places=10, max_digits=100)),
                     ('trailing_EPS', models.DecimalField(decimal_places=6, max_digits=100)),
                     ],
                 ),
        migrations.CreateModel(
                 name='Trade',
                 fields=[
                     ('id', models.AutoField(primary_key=True, serialize=False)),
                     (
                         'type',
                         models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], default='Buy', max_length=4)),
                     ('subtype',
                      models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], default='Open', max_length=5)),
                     ('initial_price', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                     ('shares', models.IntegerField(default=0)),
                     ('fee_rate', models.IntegerField(default=0)),
                     ('fee_cost', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                     ('trade_cost', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                     ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                     ('initiated', models.DateTimeField(default=django.utils.timezone.now)),
                     ('closed', models.DateTimeField(blank=True, null=True)),
                     ('gain_loss_value', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                     (
                         'gain_loss_percent',
                         models.DecimalField(blank=True, decimal_places=6, max_digits=100, null=True)),
                     ('reason', models.TextField(default='NA')),
                     ('polymorphic_ctype',
                      models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                        related_name='polymorphic_portfolio.trade_set+',
                                        to='contenttypes.ContentType')),
                     ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades',
                                                     to='portfolio.Portfolio')),
                     ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades',
                                                 to='portfolio.Stock')),
                     ],
                 options={
                     'abstract': False,
                     'base_manager_name': 'objects',
                     },
                 ),
        migrations.CreateModel(
                 name='Long',
                 fields=[
                     ('trade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                        parent_link=True, primary_key=True, serialize=False,
                                                        to='portfolio.Trade')),
                     ],
                 options={
                     'abstract': False,
                     'base_manager_name': 'objects',
                     },
                 bases=('portfolio.trade',),
                 ),
        migrations.CreateModel(
                 name='Option',
                 fields=[
                     ('trade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                        parent_link=True, primary_key=True, serialize=False,
                                                        to='portfolio.Trade')),
                     ('expiration',
                      models.DateField(default=datetime.datetime(2020, 6, 30, 3, 22, 21, 180017, tzinfo=utc))),
                     ('strike', models.DecimalField(decimal_places=2, max_digits=100)),
                     ('option_cost', models.DecimalField(decimal_places=2, max_digits=100)),
                     ],
                 options={
                     'abstract': False,
                     'base_manager_name': 'objects',
                     },
                 bases=('portfolio.trade',),
                 ),
        migrations.CreateModel(
                 name='Short',
                 fields=[
                     ('trade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                        parent_link=True, primary_key=True, serialize=False,
                                                        to='portfolio.Trade')),
                     ],
                 options={
                     'abstract': False,
                     'base_manager_name': 'objects',
                     },
                 bases=('portfolio.trade',),
                 ),
        migrations.CreateModel(
                 name='LongCall',
                 fields=[
                     ('option_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                         parent_link=True, primary_key=True, serialize=False,
                                                         to='portfolio.Option')),
                     ],
                 options={
                     'abstract': False,
                     'base_manager_name': 'objects',
                     },
                 bases=('portfolio.option',),
                 ),
        migrations.CreateModel(
                 name='LongPut',
                 fields=[
                     ('option_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                         parent_link=True, primary_key=True, serialize=False,
                                                         to='portfolio.Option')),
                     ],
                 options={
                     'abstract': False,
                     'base_manager_name': 'objects',
                     },
                 bases=('portfolio.option',),
                 ),
        migrations.CreateModel(
                 name='ShortCall',
                 fields=[
                     ('option_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                         parent_link=True, primary_key=True, serialize=False,
                                                         to='portfolio.Option')),
                     ],
                 options={
                     'abstract': False,
                     'base_manager_name': 'objects',
                     },
                 bases=('portfolio.option',),
                 ),
        migrations.CreateModel(
                 name='ShortPut',
                 fields=[
                     ('option_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                         parent_link=True, primary_key=True, serialize=False,
                                                         to='portfolio.Option')),
                     ],
                 options={
                     'abstract': False,
                     'base_manager_name': 'objects',
                     },
                 bases=('portfolio.option',),
                 ),
        ]
