# Generated by Django 3.1.2 on 2020-11-23 00:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_auto_20201005_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2021, 2, 23, 0, 48, 29, 44621, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='fee_rate',
            field=models.FloatField(default=0),
        ),
    ]
