# Generated by Django 3.1.2 on 2020-11-23 02:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_auto_20201122_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='tradeable',
            new_name='tradable',
        ),
        migrations.AlterField(
            model_name='option',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2021, 2, 23, 2, 17, 24, 372750, tzinfo=utc)),
        ),
    ]
