# Generated by Django 3.1.2 on 2020-11-24 04:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_auto_20201122_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2021, 2, 24, 4, 12, 18, 119676, tzinfo=utc)),
        ),
    ]
