# Generated by Django 3.1.2 on 2020-11-25 14:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0030_auto_20201124_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='option_type',
            field=models.CharField(choices=[('American', 'American'), ('European', 'European')], default='American', max_length=8),
        ),
        migrations.AlterField(
            model_name='option',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2021, 2, 25, 14, 55, 20, 568506, tzinfo=utc)),
        ),
    ]
