# Generated by Django 3.1.2 on 2020-12-25 05:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0030_auto_20201124_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2021, 3, 25, 5, 13, 39, 733447, tzinfo=utc)),
        ),
    ]
