# Generated by Django 3.1.2 on 2020-12-26 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0032_auto_20201125_0957'),
        ('portfolio', '0031_auto_20201225_0013'),
    ]

    operations = [
    ]
