# Generated by Django 3.1.2 on 2020-12-26 17:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0033_merge_20201226_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='tradable',
            new_name='tradeable',
        ),
        migrations.AlterField(
            model_name='option',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2021, 3, 26, 17, 40, 14, 498797, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='TradeValueHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('asset_price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('unrealized_gain_loss', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_history', to='portfolio.trade')),
            ],
        ),
    ]
