# Generated by Django 3.1.2 on 2020-12-29 02:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0034_auto_20201226_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='shares',
        ),
        migrations.AddField(
            model_name='long',
            name='shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='option',
            name='contracts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='starting_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='short',
            name='shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='option',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2021, 3, 29, 2, 11, 9, 160210, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='PortfolioValueHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=100)),
                ('unrealized_gain_loss', models.DecimalField(decimal_places=2, max_digits=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=100)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_history', to='portfolio.portfolio')),
            ],
        ),
    ]
