# Generated by Django 3.1.2 on 2020-12-29 02:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0035_auto_20201228_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2021, 3, 29, 2, 28, 16, 338142, tzinfo=utc)),
        ),
    ]
