# Generated by Django 3.1.2 on 2020-12-29 02:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0036_auto_20201228_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2021, 3, 29, 2, 35, 46, 740004, tzinfo=utc)),
        ),
    ]
