# Generated by Django 3.1.2 on 2020-12-29 02:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0037_auto_20201228_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='long',
            name='shares',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='option',
            name='contracts',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='option',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2021, 3, 29, 2, 47, 30, 881568, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='short',
            name='shares',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=100),
        ),
    ]
